const TOPICS = [
  {
    id: "array",
    name: "Arrays",
    color: "#FF6B6B",
    emoji: "📊",
    ring: "inner",
    tips: [
      "Two-pointer for in-place modifications (move zeros, remove duplicates)",
      "Use the array itself as a hash map when values are in range [1,n] — flip signs",
      "Leaders: traverse right-to-left, track max seen so far",
      "Kth smallest/largest → QuickSelect for O(n) average, or heap for O(n log k)",
      "Think: do I need extra space? Or can I modify in-place?",
    ],
    problems: [
      {
        name: "Move Zeros",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/move-zeroes/",
        leetcodeNum: 283,
        file: "Array/1-move-zeros.py",
        notes: "Two-pointer: \"slow\" marks next position for a non-zero, \"fast\" scans ahead.\n\nAlgorithm:\n• Maintain slow pointer at 0\n• For each nums[fast] != 0: swap nums[slow] and nums[fast], slow++\n• After loop, zeros are all pushed to the end\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Remove Duplicates",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
        leetcodeNum: 26,
        file: "Array/2-remove-duplicates.py",
        notes: "Input is sorted. Slow pointer marks boundary of unique elements.\n\nAlgorithm:\n• slow = 1 (first element always unique)\n• For fast from 1 to n: if nums[fast] != nums[fast-1], nums[slow++] = nums[fast]\n• Return slow (length of unique portion)\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Array Leaders",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/largest-number-after-digit-swaps-by-parity/",
        leetcodeNum: null,
        file: "Array/3-leader.py",
        notes: "A leader is greater than all elements to its right.\n\nAlgorithm:\n• Traverse right-to-left, track max_right\n• If nums[i] > max_right → it's a leader, add to result\n• Update max_right = max(max_right, nums[i])\n• Last element is always a leader\n\nTime: O(n) | Space: O(k) where k = number of leaders",
      },
      {
        name: "Find Duplicates",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
        leetcodeNum: 442,
        file: "Array/4-find-duplicates.py",
        notes: "Values in range [1,n] → use the array as a hash map by negating.\n\nAlgorithm:\n• For each value v (use abs(v) since we modify signs):\n  - idx = abs(v) - 1\n  - If nums[idx] < 0 → abs(v) is a duplicate\n  - Else: nums[idx] *= -1  (mark as visited)\n\nNo extra space needed! Time: O(n) | Space: O(1)",
      },
      {
        name: "Kth Smallest Number",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        leetcodeNum: 215,
        file: "Array/5-x-smallest-number.py",
        notes: "When values are in a known range, use counting or QuickSelect.\n\nApproach 1 – Min-Heap:\n• Push all elements, pop k times → O(n + k log n)\n\nApproach 2 – Max-Heap of size k:\n• Maintain heap of k smallest seen → O(n log k)\n\nApproach 3 – QuickSelect:\n• Partition like QuickSort, recurse only on the side containing kth element → O(n) average",
      },
    ],
  },

  {
    id: "binary-search",
    name: "Binary Search",
    color: "#4ECDC4",
    emoji: "🔍",
    ring: "inner",
    tips: [
      "Template: lo=0, hi=n-1, while lo<=hi, mid=(lo+hi)//2",
      "Lower bound = first index where arr[i] >= target (use hi = mid-1 when match)",
      "Upper bound = first index where arr[i] > target",
      "Rotated array: one half is always sorted — use that to decide search direction",
      "Binary search on the ANSWER: when searching for min/max of a condition",
      "lo after loop = insertion point (answer for \"where would target go\")",
    ],
    problems: [
      {
        name: "Binary Search",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/binary-search/",
        leetcodeNum: 704,
        file: "BinarySearch/1.binary-search.py",
        notes: "Classic template.\n\nAlgorithm:\n• lo, hi = 0, len(nums)-1\n• while lo <= hi:\n  - mid = (lo+hi)//2\n  - if nums[mid] == target: return mid\n  - if target < nums[mid]: hi = mid-1\n  - else: lo = mid+1\n• return -1\n\nTime: O(log n) | Space: O(1)",
      },
      {
        name: "Search Insert Position",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/search-insert-position/",
        leetcodeNum: 35,
        file: "BinarySearch/2.search-index.py",
        notes: "This is the lower bound — first position where nums[i] >= target.\n\nKey insight: after the loop ends, lo = the insertion point.\n\nAlgorithm:\n• Standard binary search but when nums[mid]==target return mid\n• After loop: return lo\n• lo will be the index where target should be inserted to keep sorted order\n\nTime: O(log n) | Space: O(1)",
      },
      {
        name: "Search in 2D Matrix",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/search-a-2d-matrix/",
        leetcodeNum: 74,
        file: "BinarySearch/3-binary-search-matrix.py",
        notes: "Treat m×n matrix as a flat sorted array of m*n elements.\n\nKey insight: index i maps to (i//n, i%n) in the matrix.\n\nAlgorithm:\n• lo=0, hi=m*n-1\n• mid = (lo+hi)//2\n• matrix_val = matrix[mid//n][mid%n]\n• Compare and narrow like standard binary search\n\nTime: O(log(m*n)) | Space: O(1)",
      },
      {
        name: "Search in Rotated Array",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        leetcodeNum: 33,
        file: "BinarySearch/4-rotated-sorted-array.py",
        notes: "At any mid point, one half is always sorted.\n\nAlgorithm:\n• If nums[lo] <= nums[mid]: left half is sorted\n  - If lo <= target < nums[mid]: search left (hi=mid-1)\n  - Else: search right (lo=mid+1)\n• Else: right half is sorted\n  - If nums[mid] < target <= hi: search right\n  - Else: search left\n\nTime: O(log n) | Space: O(1)",
      },
      {
        name: "Min in Rotated Array",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
        leetcodeNum: 153,
        file: "BinarySearch/5-min-in-rotated-sorted-array.py",
        notes: "The minimum is in the unsorted half.\n\nAlgorithm:\n• Compare nums[mid] with nums[hi]\n• If nums[mid] > nums[hi]: minimum is in right half (lo=mid+1)\n• Else: minimum is in left half including mid (hi=mid)\n• When lo==hi, that's the minimum\n\nTime: O(log n) | Space: O(1)",
      },
      {
        name: "Min in Rotated (Duplicates)",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/",
        leetcodeNum: 154,
        file: "BinarySearch/6-min-in-rotated-duplicate.py",
        notes: "When duplicates allowed, nums[mid]==nums[hi] makes direction ambiguous.\n\nAlgorithm:\n• Same as LC 153 but add: if nums[mid] == nums[hi]: hi -= 1 (just shrink)\n• This handles the ambiguous case, worst case O(n) when all duplicates\n\nTime: O(log n) avg, O(n) worst | Space: O(1)",
      },
      {
        name: "Single Element in Sorted Array",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
        leetcodeNum: 540,
        file: "BinarySearch/7-find-single-element.py",
        notes: "Use parity of index to determine which side the single element is on.\n\nKey insight:\n• Before the single element: pairs are at (even, odd) indices\n• After the single element: pairs shift to (odd, even) indices\n\nAlgorithm:\n• If mid is even: check nums[mid]==nums[mid+1]\n  - Yes → single is in right half (lo=mid+2)\n  - No → single is in left half including mid (hi=mid)\n• If mid is odd: similar logic reversed\n\nTime: O(log n) | Space: O(1)",
      },
      {
        name: "Find Peak Element",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/find-peak-element/description/",
        leetcodeNum: 162,
        file: "BinarySearch/8-peak-element.py",
        notes: "Key insight: Follow ascending slope—go right if mid < mid+1 (slope up), go left if mid > mid+1 (slope down). Algorithm: Binary search always moves toward peak, guaranteed to find one. Time: O(log n) | Space: O(1)",
      },
      {
        name: "Minimum Speed to Arrive On Time (Unbounded)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/minimum-speed-to-arrive-on-time/description/",
        leetcodeNum: 1870,
        file: "BinarySearch/9-unbounded-case.py",
        notes: "Key insight: Right bound set to 10^7 (unbounded)—binary search on answer. Algorithm: Calculate time with candidate speed (using ceil for all but last segment), move boundary if feasible. Time: O(n log(max_speed)) | Space: O(1)",
      },
      {
        name: "Binary Search on Answer: Eating Bananas",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/minimum-eating-speed/",
        leetcodeNum: 875,
        file: "BinarySearch/10-bs-on-answers.py",
        notes: "Key insight: Problem asks for minimum speed—binary search on answer space instead of array. Algorithm: Find minimum k where we can eat all piles in h hours by checking feasibility with math.ceil. Time: O(n log(max_pile)) | Space: O(1)",
      },
    ],
  },

  {
    id: "linked-list",
    name: "Linked Lists",
    color: "#45B7D1",
    emoji: "🔗",
    ring: "inner",
    tips: [
      "Draw pointer manipulation on paper before coding",
      "Use a dummy head node to handle edge cases at the head",
      "Fast/slow pointers solve: cycle detection, middle node, nth from end",
      "Floyd's cycle detection: fast moves 2x, slow moves 1x",
      "After cycle detected, move one pointer to head; advance both by 1 → cycle start",
      "Always check for null before accessing .next",
    ],
    problems: [
      {
        name: "Reverse Linked List",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/reverse-linked-list/",
        leetcodeNum: 206,
        file: "LinkedList/Reverse.py",
        notes: "Three approaches covered in the file:\n\nIterative (best):\n• prev=None, curr=head\n• While curr: next=curr.next, curr.next=prev, prev=curr, curr=next\n• Return prev\n\nRecursive:\n• reverse(head.next) returns new_head\n• head.next.next = head; head.next = None\n• Return new_head\n\nStack: push all, rebuild (O(n) space)\n\nTime: O(n) | Space: O(1) iterative",
      },
      {
        name: "Remove Nth from End",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
        leetcodeNum: 19,
        file: "LinkedList/DeleteAtnth.py",
        notes: "Two-pointer gap technique — one pass!\n\nAlgorithm:\n• Use dummy head, fast and slow both start at dummy\n• Advance fast by n+1 steps\n• Then move both until fast is None\n• slow is now at the node BEFORE the one to delete\n• slow.next = slow.next.next\n\nWhy n+1? So slow lands one before the target, not on it.\n\nTime: O(L) | Space: O(1)",
      },
      {
        name: "Floyd's Cycle Detection",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/linked-list-cycle/",
        leetcodeNum: 141,
        file: "LinkedList/Floyds-cycle-detection.py",
        notes: "Fast moves 2 steps, slow moves 1 step.\n\nAlgorithm:\n• If fast or fast.next is None → no cycle, return False\n• If fast == slow → cycle exists, return True\n\nMathematical proof: in a cycle of length L, fast gains 1 step per iteration on slow, so they meet in L iterations.\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Detect Cycle Start",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/linked-list-cycle-ii/",
        leetcodeNum: 142,
        file: "LinkedList/detect-cycle-start.py",
        notes: "After Floyd's detection finds the meeting point:\n\nKey insight (math):\n• Let F = distance from head to cycle start\n• Let a = distance from cycle start to meeting point\n• Meeting point: F ≡ a (mod L)\n• So distance from meeting point back to cycle start = F\n\nAlgorithm:\n• Reset one pointer to head\n• Advance both pointers 1 step at a time\n• Where they meet = cycle start\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Floyd's Applications",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/happy-number/",
        leetcodeNum: 202,
        file: "LinkedList/floyd-application.py",
        notes: "Floyd's algorithm isn't just for linked lists — any function f(x) applied repeatedly creates a \"linked list\" structure.\n\nHappy Number:\n• next(n) = sum of squares of digits\n• If this sequence enters a cycle not containing 1 → not happy\n• Apply Floyd's: fast=next(next(n)), slow=next(n)\n\nFind Duplicate in Array (LC 287):\n• Treat array values as next pointers\n• nums[i] points to nums[nums[i]]\n• Cycle exists because duplicate creates two paths to same node",
      },
      {
        name: "Linked List Implementation",
        difficulty: "Easy",
        leetcode: null,
        leetcodeNum: null,
        file: "LinkedList/implement.py",
        notes: "Key insight: Basic LinkedList and DoublyLinkedList operations—insert at beginning/end. Algorithm: Node creation, traversal, pointer manipulation. Time: O(n) for end insertion (traverse), O(1) for begin | Space: O(1)",
      },
    ],
  },

  {
    id: "trees",
    name: "Trees",
    color: "#96CEB4",
    emoji: "🌳",
    ring: "inner",
    tips: [
      "Inorder of BST = sorted sequence — validate BST, find kth smallest",
      "For path problems: DFS returning values bottom-up (post-order style)",
      "Level-order = BFS with queue, track level size for per-level processing",
      "Diameter/LCA: use a global variable updated during DFS recursion",
      "Height of null = 0, height of leaf = 1",
      "Balanced: height difference of left and right subtrees ≤ 1 at every node",
    ],
    problems: [
      {
        name: "Inorder Traversal",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
        leetcodeNum: 94,
        file: "Trees/2-traversal.py",
        notes: "Left → Root → Right\n\nRecursive (simple):\n• inorder(node.left); visit(node); inorder(node.right)\n\nIterative (uses explicit stack):\n• curr = root, stack = []\n• while curr or stack:\n  - Go left: while curr: stack.append(curr); curr=curr.left\n  - Pop: curr = stack.pop(); visit(curr); curr = curr.right\n\nFor BST: this gives sorted order!\n\nTime: O(n) | Space: O(h)",
      },
      {
        name: "Preorder Traversal",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
        leetcodeNum: 144,
        file: "Trees/2-traversal.py",
        notes: "Root → Left → Right\n\nIterative with stack:\n• Push root to stack\n• While stack: pop node, visit it, push right then left\n• (Push right first so left is processed first)\n\nUse case: serialize tree, copy tree structure\n\nTime: O(n) | Space: O(h)",
      },
      {
        name: "Postorder Traversal",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
        leetcodeNum: 145,
        file: "Trees/2-traversal.py",
        notes: "Left → Right → Root\n\nIterative trick:\n• Do modified preorder: Root → Right → Left (push left then right)\n• Collect results in a list\n• Reverse the list at the end\n\nUse case: delete tree, evaluate expression trees\n\nTime: O(n) | Space: O(h)",
      },
      {
        name: "Level Order Traversal",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        leetcodeNum: 102,
        file: "Trees/2-traversal.py",
        notes: "BFS separates nodes by level.\n\nAlgorithm:\n• queue = deque([root])\n• while queue:\n  - level_size = len(queue)\n  - For _ in range(level_size):\n    • node = queue.popleft()\n    • add to current level\n    • enqueue node.left and node.right if not None\n  - append current level to result\n\nKey: record queue size at start of each level iteration\n\nTime: O(n) | Space: O(w) where w is max width",
      },
      {
        name: "Binary Tree Level Order Traversal",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        leetcodeNum: 102,
        file: "Trees/3-level-order.py",
        notes: "Key insight: BFS with queue size tracking for level boundaries. Algorithm: Process level by level using queue size to determine when level ends. Time: O(n) | Space: O(w) where w=width",
      },
      {
        name: "Binary Tree Zigzag Level Order",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
        leetcodeNum: 103,
        file: "Trees/4-zig-zag.py",
        notes: "Key insight: Alternate direction per level—reverse every other level. Algorithm: BFS with boolean flag, reverse level if flag false. Time: O(n) | Space: O(w)",
      },
      {
        name: "Odd Even Level Order",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Trees/5-odd-even.py",
        notes: "Key insight: Separate processing of odd/even levels in traversal. Algorithm: BFS with level counter, distinct processing per level type. Time: O(n) | Space: O(w)",
      },
      {
        name: "Construct Binary Tree from Inorder & Postorder",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
        leetcodeNum: 106,
        file: "Trees/6-tree-construction.py",
        notes: "Key insight: Last element in postorder = root, find root in inorder to partition left/right. Algorithm: Recursive construction by finding root position and splitting arrays. Time: O(n²) | Space: O(h)",
      },
      {
        name: "Construct Binary Tree from Preorder & Inorder",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
        leetcodeNum: 105,
        file: "Trees/7-build-tree-1.py",
        notes: "Key insight: First element in preorder = root, find in inorder to partition left/right subtrees. Algorithm: Recursive construction with array slicing. Time: O(n²) worst case | Space: O(h)",
      },
      {
        name: "Maximum Binary Tree",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/maximum-binary-tree/description/",
        leetcodeNum: 654,
        file: "Trees/8-max-binary-tree.py",
        notes: "Key insight: Root = max element, recursively construct left and right from subarrays. Algorithm: Find max, split array, recursive construction. Time: O(n²) worst case | Space: O(h)",
      },
      {
        name: "Construct BST from Preorder",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/",
        leetcodeNum: 1008,
        file: "Trees/9-construct-bst.py",
        notes: "Key insight: Sort preorder to get inorder, then use inorder+preorder construction algorithm. Algorithm: Create both sequences, build tree via partition. Time: O(n log n) | Space: O(h)",
      },
      {
        name: "Maximum Depth of Binary Tree",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        leetcodeNum: 104,
        file: "Trees/10-max-depth.py",
        notes: "Key insight: Recursive—return 1 + max(left_depth, right_depth). Algorithm: DFS post-order traversal, compute height bottom-up. Time: O(n) | Space: O(h)",
      },
      {
        name: "Balanced Binary Tree",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/balanced-binary-tree/",
        leetcodeNum: 110,
        file: "Trees/11-check-balance-tree.py",
        notes: "Key insight: Sentinel pattern—return -1 if unbalanced, else return height. Algorithm: DFS checking height difference ≤1 at each node. Time: O(n) | Space: O(h)",
      },
      {
        name: "Binary Tree Diameter",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/diameter-of-binary-tree/",
        leetcodeNum: 543,
        file: "Trees/12-diameter.py",
        notes: "Key insight: Diameter = longest path between any two nodes = max(left_height + right_height). Algorithm: DFS post-order, track max sum at each node. Time: O(n) | Space: O(h)",
      },
      {
        name: "Path Sum (Root to Leaf)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/path-sum-ii/",
        leetcodeNum: 113,
        file: "Trees/13-path-sum.py",
        notes: "Key insight: Find all paths where sum = target, backtracking with path restoration. Algorithm: DFS with current path list, append at leaf if sum matches. Time: O(n·h) | Space: O(h)",
      },
      {
        name: "Sum Root to Leaf Numbers",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
        leetcodeNum: 129,
        file: "Trees/14-sum-root-to-leaf.py",
        notes: "Key insight: Treat each path as number—multiply by 10 and add current node value. Algorithm: DFS computing numbers top-down, sum leaf values. Time: O(n) | Space: O(h)",
      },
      {
        name: "Insufficient Nodes in Root to Leaf Paths",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/insufficient-nodes-in-root-to-leaf-paths/description/",
        leetcodeNum: 1080,
        file: "Trees/15-insufficient-nodes.py",
        notes: "Key insight: Remove nodes whose path sum < limit. Algorithm: DFS returns None if insufficient, parent captures return value to update pointer. Time: O(n) | Space: O(h)",
      },
      {
        name: "Lowest Common Ancestor",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
        leetcodeNum: 236,
        file: "Trees/16-LCA.py",
        notes: "Key insight: Post-order DFS—LCA is first node where both p,q found in subtrees. Algorithm: If both subtrees have target, current is LCA; else return non-null side. Time: O(n) | Space: O(h)",
      },
      {
        name: "Minimum Absolute Difference in BST",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/",
        leetcodeNum: 530,
        file: "Trees/17-BST.py",
        notes: "Key insight: Inorder traversal of BST = sorted array. Min diff = consecutive elements in sorted order. Time: O(n) | Space: O(h)",
      },
      {
        name: "Maximum Difference Between Node and Ancestor",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/maximum-difference-between-node-and-ancestor/description/",
        leetcodeNum: 1026,
        file: "Trees/17-maxDiff.py",
        notes: "Key insight: Track min/max ancestor values top-down. Difference = max_ancestor - min_ancestor at each node. Algorithm: DFS passing min/max from ancestors. Time: O(n) | Space: O(h)",
      },
    ],
  },

  {
    id: "graph",
    name: "Graphs",
    color: "#FECA57",
    emoji: "🕸️",
    ring: "inner",
    tips: [
      "Matrix grid problems → think graph with 4-directional BFS/DFS",
      "Multi-source BFS: add ALL sources to queue before starting",
      "Cycle in directed graph → DFS with 3 states: 0=unvisited, 1=in-stack, 2=done",
      "Cycle in undirected → BFS/DFS tracking parent node",
      "Topological sort: valid only for DAGs (directed acyclic graphs)",
      "Kahn's algorithm: process nodes with 0 in-degree first",
      "Dijkstra: min-heap + dist array, works only with non-negative weights",
      "BFS for unweighted shortest path; Dijkstra for weighted",
    ],
    problems: [
      {
        name: "BFS – Number of Islands",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/number-of-islands/",
        leetcodeNum: 200,
        file: "Graph/3-bfs.py",
        notes: "BFS from each unvisited land cell, mark all connected cells as visited.\n\nAlgorithm:\n• For each cell: if grid[r][c]=='1' and unvisited:\n  - BFS/DFS from it, mark all connected '1's as visited\n  - Increment island count\n\nBFS template:\n• Queue with (row, col)\n• Mark visited WHEN ENQUEUING (not when processing)\n• Check 4 neighbors, enqueue valid unvisited land\n\nTime: O(m*n) | Space: O(min(m,n)) for queue",
      },
      {
        name: "DFS – Connected Components",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/number-of-provinces/",
        leetcodeNum: 547,
        file: "Graph/2-connected-components.py",
        notes: "Count distinct connected components in a graph.\n\nAlgorithm:\n• visited = set()\n• For each node 0..n-1: if not visited:\n  - DFS from it (marks all reachable nodes visited)\n  - Increment component count\n\nDFS marks visited when ENTERING the node.\n\nAdjacency list from matrix: isConnected[i][j] == 1\n\nTime: O(n²) | Space: O(n)",
      },
      {
        name: "Rotten Oranges",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/rotting-oranges/",
        leetcodeNum: 994,
        file: "Graph/5-rotten-oranges.py",
        notes: "Multi-source BFS — all rotten oranges rot neighbors simultaneously.\n\nAlgorithm:\n• Add ALL rotten oranges to queue, count fresh\n• BFS level by level (each level = 1 minute)\n• For each rotten orange, check 4 neighbors:\n  - If fresh: make rotten, enqueue, fresh--\n• If fresh > 0 after BFS: return -1\n• Return minute count\n\nKey: add all sources BEFORE starting BFS\n\nTime: O(m*n) | Space: O(m*n)",
      },
      {
        name: "Flood Fill",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/flood-fill/",
        leetcodeNum: 733,
        file: "Graph/6-flood-filling.py",
        notes: "DFS/BFS changing color of connected pixels with same original color.\n\nEdge case: if new color == original color, return early (avoid infinite loop).\n\nAlgorithm:\n• orig = image[sr][sc]\n• If orig == newColor: return image\n• DFS from (sr, sc):\n  - Change color, recurse on 4 neighbors with same orig color\n\nTime: O(m*n) | Space: O(m*n) recursion stack",
      },
      {
        name: "Detect Cycle (Directed Graph)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/course-schedule/",
        leetcodeNum: 207,
        file: "Graph/7-detect-cycle-in-directed.py",
        notes: "DFS with 3-color marking.\n\nStates:\n• 0 = unvisited (white)\n• 1 = in current DFS path (gray)\n• 2 = fully processed (black)\n\nAlgorithm:\n• For each unvisited node: run DFS\n• Mark node gray when entering, black when done\n• If DFS reaches a gray node → back edge → CYCLE!\n\nApplication: Course Schedule — can you finish all courses?\n\nTime: O(V+E) | Space: O(V)",
      },
      {
        name: "Bipartite Check",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/is-graph-bipartite/",
        leetcodeNum: 785,
        file: "Graph/10-bipartide-graph.py",
        notes: "Try to 2-color the graph — adjacent nodes must have different colors.\n\nAlgorithm (BFS):\n• color[] = -1 for all nodes\n• For each uncolored node: BFS, color it 0\n• For each neighbor: if same color → NOT bipartite\n• If uncolored: color it 1-current, enqueue\n\nBipartite ↔ no odd-length cycles ↔ can be 2-colored\n\nTime: O(V+E) | Space: O(V)",
      },
      {
        name: "Topological Sort (DFS)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/course-schedule-ii/",
        leetcodeNum: 210,
        file: "Graph/11-topological-sort.py",
        notes: "DFS-based: add node to result AFTER visiting all its neighbors.\n\nAlgorithm:\n• visited = set(), result = []\n• For each unvisited node: DFS\n  - Mark as visiting (in-path)\n  - Visit all unvisited neighbors\n  - Append to result, mark done\n• Reverse result = topological order\n\nIf cycle detected: no valid order\n\nTime: O(V+E) | Space: O(V)",
      },
      {
        name: "Kahn's Algorithm (BFS Topo)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/course-schedule-ii/",
        leetcodeNum: 210,
        file: "Graph/12-kahns.py",
        notes: "BFS-based topological sort using in-degree counts.\n\nAlgorithm:\n• Compute in-degree for every node\n• Enqueue all nodes with in-degree 0\n• While queue:\n  - Process node, add to result\n  - For each neighbor: in_degree[neighbor]--\n  - If in_degree[neighbor] == 0: enqueue\n• If result.length < n → cycle exists\n\nIntuition: process nodes with no prerequisites first.\n\nTime: O(V+E) | Space: O(V)",
      },
      {
        name: "Dijkstra's Algorithm",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/network-delay-time/",
        leetcodeNum: 743,
        file: "Graph/15.djkstras.py",
        notes: "Greedy shortest path with min-heap. Only works with non-negative weights.\n\nAlgorithm:\n• dist[] = [∞]*n; dist[src] = 0\n• min_heap = [(0, src)]\n• While heap: pop (d, u)\n  - If d > dist[u]: skip (stale entry)\n  - For each neighbor v with weight w:\n    - If dist[u]+w < dist[v]: update dist[v], push to heap\n\nTime: O((V+E) log V) | Space: O(V)",
      },
      {
        name: "Min Effort Path",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/path-with-minimum-effort/",
        leetcodeNum: 1631,
        file: "Graph/18-min-effort.py",
        notes: "Modified Dijkstra: minimize maximum difference along path.\n\nKey change from standard Dijkstra:\n• Instead of minimizing sum, minimize max(abs(diff)) along path\n• effort[r][c] = min effort to reach (r,c)\n• Relaxation: new_effort = max(curr_effort, abs(curr-neighbor))\n• If new_effort < effort[r][c]: update and push\n\nTime: O(m*n*log(m*n)) | Space: O(m*n)",
      },
      {
        name: "Cheapest Flights (K Stops)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        leetcodeNum: 787,
        file: "Graph/19-cheapest-flight.py",
        notes: "Bellman-Ford with K iterations (at most K+1 edges).\n\nAlgorithm:\n• prices[] = [∞]*n; prices[src] = 0\n• Repeat K+1 times:\n  - temp = prices.copy()  ← CRUCIAL: use previous iteration's prices\n  - For each edge (u,v,w): if prices[u]+w < temp[v]: temp[v] = prices[u]+w\n  - prices = temp\n\nWhy copy? Prevents using more than k stops by accident.\n\nTime: O(K*(V+E)) | Space: O(V)",
      },
      {
        name: "0-1 Matrix",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/01-matrix/",
        leetcodeNum: 542,
        file: "Graph/9-01-Matrix.py",
        notes: "Multi-source BFS from all 0s simultaneously — much faster than BFS from each 1.\n\nAlgorithm:\n• dist[] = [∞ for 1s, 0 for 0s]\n• Queue starts with ALL 0-cells\n• BFS: for each cell, update unvisited neighbors with dist+1\n• No need for explicit visited array — ∞ means unvisited\n\nBrute force (BFS from each 1) would be O(m²n²).\nThis approach: O(m*n)\n\nTime: O(m*n) | Space: O(m*n)",
      },
      {
        name: "Snakes and Ladders",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/snakes-and-ladders/",
        leetcodeNum: 909,
        file: "Graph/21-snake-ladders.py",
        notes: "BFS for minimum number of dice rolls (unweighted shortest path).\n\nTricky part — boustrophedon indexing (board fills alternating left-right):\n• Square s → row = (s-1)//n, col = (s-1)%n\n• If row is even (from bottom): col stays; if odd: col = n-1-col\n• Then actual row from top = n-1-row\n\nBFS from square 1, explore squares s+1 to s+6 (dice).\nIf cell has snake/ladder, jump to destination.\n\nTime: O(n²) | Space: O(n²)",
      },
      {
        name: "Graph Representation (Matrix & List)",
        difficulty: "Easy",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/1-representation.py",
        notes: "Key insight: Matrix O(V²) space, List O(V+E)—choose based on density. Algorithm: Adjacency matrix vs list vs defaultdict implementations with trade-offs. Time: O(V²+E) matrix, O(V+E) list | Space: O(V²) vs O(V+E)",
      },
      {
        name: "Depth-First Search (DFS)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/4.dfs.py",
        notes: "Key insight: Recursive or iterative DFS for topological sort, cycle detection, paths. Algorithm: Multiple DFS patterns—standard, with path, all paths, cycle detection. Time: O(V+E) | Space: O(V)",
      },
      {
        name: "BFS Practice",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/3-bfs-practice.py",
        notes: "Key insight: Multiple queue implementations with different complexities. Algorithm: Compare deque O(1), list index O(V+E), list.pop(0) O(V²+E). Only use deque for O(V+E). Time: O(V+E) optimal | Space: O(V)",
      },
      {
        name: "Cycle Detection (Undirected, BFS)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/8-detect-cycle-undirected-bfs.py",
        notes: "Key insight: Track parent in BFS—cycle if reach visited node that's not parent. Algorithm: BFS with parent tracking, check neighbors; non-parent revisit = cycle. Time: O(V+E) | Space: O(V)",
      },
      {
        name: "Cycle Detection (Undirected, DFS)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/8-detect-cycle-undirected-dfs.py",
        notes: "Key insight: Track parent in DFS—cycle exists if visited neighbor is not parent. Algorithm: Recursive DFS with parent parameter, return true if cycle found. Time: O(V+E) | Space: O(V)",
      },
      {
        name: "Shortest Path in DAG (Topological Sort)",
        difficulty: "Hard",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/13.shortest-path-topo.py",
        notes: "Key insight: Process DAG nodes in topological order—optimal O(V+E) unlike Dijkstra O(V log V). Handles negative weights. Algorithm: Topo sort via DFS, relax edges in order. Time: O(V+E) | Space: O(V)",
      },
      {
        name: "Shortest Path in Binary Matrix (BFS)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/14.shortest-path-bfs.py",
        notes: "Key insight: Unweighted grid shortest path—use BFS with 8 directions. Early terminate on destination. Algorithm: BFS level-order with 8-directional movement, check boundary & obstacles. Time: O(n²) | Space: O(n²)",
      },
      {
        name: "Dijkstra's Algorithm",
        difficulty: "Hard",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/16-djkstras.py",
        notes: "Key insight: Greedy shortest path using min-heap for non-negative weights. Algorithm: Always process nearest unvisited node, relax edges. With path reconstruction via parent tracking. Time: O((V+E) log V) | Space: O(V)",
      },
      {
        name: "Shortest Path Matrix (Floyd-Warshall)",
        difficulty: "Hard",
        leetcode: null,
        leetcodeNum: null,
        file: "Graph/17-shortestpath-matrix.py",
        notes: "Key insight: All-pairs shortest path using intermediate nodes. Algorithm: Triple nested loop over intermediate node k, check if path through k is shorter. Time: O(V³) | Space: O(V²)",
      },
    ],
  },

  {
    id: "dp",
    name: "Dynamic Programming",
    color: "#FF9FF3",
    emoji: "🧮",
    ring: "inner",
    tips: [
      "Identify: overlapping subproblems + optimal substructure",
      "Time Complexity = (Number of States) × (Work per State)",
      "Top-down = recursion + memoization dict. Bottom-up = fill table iteratively.",
      "0/1 Knapsack: each item used at most once. Unbounded: items reusable.",
      "LCS pattern: match → 1+dp[i-1][j-1], else → max(dp[i-1][j], dp[i][j-1])",
      "Partition DP (MCM): try all split points i≤k<j, take min/max",
      "Space optimization: often 2D DP → 1D with careful iteration order",
    ],
    problems: [
      {
        name: "0/1 Knapsack",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/partition-equal-subset-sum/",
        leetcodeNum: 416,
        file: "DP/1-Knapsack/0-1-knapsack/bottom-up.py",
        notes: "Classic 0/1 Knapsack: each item used at most once.\n\nRecurrence:\n• dp[i][w] = max value using first i items with weight limit w\n• dp[i][w] = max(dp[i-1][w], val[i] + dp[i-1][w-wt[i]]) if wt[i] <= w\n• else: dp[i][w] = dp[i-1][w]\n\nSpace optimization: iterate w from right to left in 1D array.\n• dp[w] = max(dp[w], val[i] + dp[w-wt[i]])\n\nTime: O(n×W) | Space: O(W) optimized",
      },
      {
        name: "Subset Sum",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/partition-equal-subset-sum/",
        leetcodeNum: 416,
        file: "DP/1-Knapsack/1-subsets-sum/bottom-up.py",
        notes: "Can we form target sum from subset?\n\nRecurrence (boolean DP):\n• dp[i][s] = True if sum s achievable using first i elements\n• dp[i][s] = dp[i-1][s] OR (s>=nums[i] AND dp[i-1][s-nums[i]])\n• Base: dp[i][0] = True for all i (empty subset sums to 0)\n\n1D optimization: iterate sum from RIGHT to LEFT\n• dp[s] |= dp[s - nums[i]]\n\nTime: O(n×S) | Space: O(S)",
      },
      {
        name: "Partition Equal Subset Sum",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/partition-equal-subset-sum/",
        leetcodeNum: 416,
        file: "DP/1-Knapsack/2-subset-partition.py",
        notes: "Split array into two equal-sum subsets.\n\nKey insight:\n• Only possible if total sum is even\n• Reduce to: can we find a subset summing to total//2?\n• This is exactly the Subset Sum problem!\n\nAlgorithm:\n• If sum % 2 != 0: return False\n• target = sum // 2\n• Run subset sum DP for target\n• Return dp[target]\n\nTime: O(n×S/2) | Space: O(S/2)",
      },
      {
        name: "Count Subsets with Sum",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/target-sum/",
        leetcodeNum: 494,
        file: "DP/1-Knapsack/3-count-of-subset-sum/top-down.py",
        notes: "Count the number of subsets summing to a target.\n\nRecurrence (count DP):\n• dp[i][s] = count of subsets from first i elements summing to s\n• dp[i][s] = dp[i-1][s] + dp[i-1][s-nums[i]]  (exclude + include)\n• Base: dp[0][0] = 1\n\nFor Target Sum (LC 494):\n• Assign + or - to each element\n• P - N = target and P + N = sum → P = (sum+target)/2\n• Count subsets summing to (sum+target)/2\n\nTime: O(n×S) | Space: O(S)",
      },
      {
        name: "Min Subset Sum Difference",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/last-stone-weight-ii/",
        leetcodeNum: 1049,
        file: "DP/1-Knapsack/4-min-subset-sum-diff/top-down.py",
        notes: "Partition array into two groups minimizing |sum1 - sum2|.\n\nKey insight:\n• sum1 + sum2 = total, minimize |total - 2*sum1|\n• Find all achievable subset sums ≤ total//2 (last row of dp)\n• Answer = min(total - 2*s) for all achievable s ≤ total//2\n\nBuild dp[s] = True/False like subset sum, then scan dp[0..total//2] for the largest True value.\n\nTime: O(n×total) | Space: O(total)",
      },
      {
        name: "Rod Cutting",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/integer-break/",
        leetcodeNum: 343,
        file: "DP/2-Unbounded-Knapsack/1-rod-cutting.py",
        notes: "Unbounded knapsack — can cut the same length multiple times.\n\nRecurrence:\n• dp[w] = max revenue from rod of length w\n• For each length l (1 to w): dp[w] = max(dp[w], price[l] + dp[w-l])\n• Outer loop: rod length w; inner loop: cut length l\n\nUnbounded difference from 0/1:\n• Iterate w from LEFT to RIGHT in 1D (allows reuse)\n• vs. 0/1 which iterates right to left\n\nTime: O(n²) | Space: O(n)",
      },
      {
        name: "Coin Change (Min Coins)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/coin-change/",
        leetcodeNum: 322,
        file: "DP/2-Unbounded-Knapsack/2-coin-change-prob.py",
        notes: "Minimum coins to make an amount. Classic unbounded knapsack.\n\nRecurrence:\n• dp[a] = min coins to make amount a\n• dp[0] = 0, dp[a] = ∞ initially\n• For each coin c, for each a from c to amount:\n  - dp[a] = min(dp[a], 1 + dp[a-c])\n\nAnswer: dp[amount] (if still ∞, impossible)\n\nOrder: iterate coins in outer loop, amounts in inner.\n\nTime: O(n*amount) | Space: O(amount)",
      },
      {
        name: "Coin Change 2 (Ways)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/coin-change-ii/",
        leetcodeNum: 518,
        file: "DP/2-Unbounded-Knapsack/3-coin-change-2.py",
        notes: "Count the number of combinations (not permutations) summing to amount.\n\nCrucial loop order:\n• Outer loop: COINS (each coin processed once as a \"type\")\n• Inner loop: amounts from coin to amount\n• dp[a] += dp[a - coin]\n\nWhy this order?\n• Ensures we count combinations, not permutations\n• Each coin type considered in a single pass\n\nIf inner loop was outer: we'd count permutations (different orderings as separate)\n\nTime: O(n*amount) | Space: O(amount)",
      },
      {
        name: "Longest Common Subsequence",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/longest-common-subsequence/",
        leetcodeNum: 1143,
        file: "DP/3-LCS/1-lcs.py",
        notes: "Subsequence = need not be contiguous.\n\nRecurrence:\n• dp[i][j] = LCS of s1[:i] and s2[:j]\n• If s1[i-1] == s2[j-1]: dp[i][j] = 1 + dp[i-1][j-1]\n• Else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n• Base: dp[0][j] = dp[i][0] = 0\n\nDifference from LCS substring:\n• When chars don't match: take max of skipping either char\n• Substring would set dp[i][j] = 0 here\n\nTime: O(m*n) | Space: O(m*n) → can optimize to O(min(m,n))",
      },
      {
        name: "Longest Common Substring",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/maximum-length-of-repeated-subarray/",
        leetcodeNum: 718,
        file: "DP/3-LCS/2-longest-common-substring.py",
        notes: "Substring = must be contiguous.\n\nRecurrence:\n• dp[i][j] = length of common CONTIGUOUS substring ending at s1[i] and s2[j]\n• If s1[i-1] == s2[j-1]: dp[i][j] = 1 + dp[i-1][j-1]\n• Else: dp[i][j] = 0  ← KEY DIFFERENCE from LCS\n• Track global max = answer\n\nIntuition: reset to 0 whenever characters don't match (contiguity broken).\n\nTime: O(m*n) | Space: O(m*n)",
      },
      {
        name: "Shortest Common Supersequence",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/shortest-common-supersequence/",
        leetcodeNum: 1092,
        file: "DP/3-LCS/4-shortest-common-superseq.py",
        notes: "Shortest string containing both s1 and s2 as subsequences.\n\nLength formula:\n• SCS_length = len(s1) + len(s2) - LCS(s1, s2)\n\nReconstruction (trace LCS table):\n• If chars match: include ONCE, move both i,j back\n• If dp[i-1][j] > dp[i][j-1]: include s1[i-1], move i back\n• Else: include s2[j-1], move j back\n• Append remaining chars of whichever string has leftovers\n\nTime: O(m*n) | Space: O(m*n)",
      },
      {
        name: "Wildcard Matching",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/wildcard-matching/",
        leetcodeNum: 44,
        file: "DP/wildcard.py",
        notes: "\"?\" matches any single char. \"*\" matches any sequence (including empty).\n\nRecurrence:\n• dp[i][j] = True if pattern[:i] matches string[:j]\n• If pattern[i-1] == string[j-1] or pattern[i-1] == \"?\": dp[i][j] = dp[i-1][j-1]\n• If pattern[i-1] == \"*\":\n  - Match empty: dp[i][j] = dp[i-1][j]  (skip the *)\n  - Match one more: dp[i][j] |= dp[i][j-1]  (extend *)\n• Base: dp[0][0]=True, dp[i][0]=True if pattern[:i] all '*'\n\nTime: O(m*n) | Space: O(m*n)",
      },
      {
        name: "0/1 Knapsack (Top-Down Memoization)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/1-Knapsack/0-1-knapsack/top-down.py",
        notes: "Key insight: For each item, choose to include (take profit, reduce capacity) or skip. Algorithm: Recursive with memoization on (capacity, item_index). Time: O(n·capacity) | Space: O(n·capacity) + call stack",
      },
      {
        name: "Subset Sum (Recursion)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/1-Knapsack/1-subsets-sum/recursion.py",
        notes: "Key insight: For each element, decide to include or exclude to form target sum. Algorithm: Backtracking—if current sum matches target, return true; try both choices. Time: O(2^n) | Space: O(n) call stack",
      },
      {
        name: "Subset Sum (Top-Down DP)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/1-Knapsack/1-subsets-sum/top-down.py",
        notes: "Key insight: Memoize on (sum, index) to avoid recomputation of same subproblems. Algorithm: DP table where dp[sum][n]=true if subset of first n elements makes sum. Time: O(sum·n) | Space: O(sum·n) + stack",
      },
      {
        name: "Partition Equal Subset Sum",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/partition-equal-subset-sum/description/",
        leetcodeNum: 416,
        file: "DP/1-Knapsack/2-subset-partition/top-down.py",
        notes: "Key insight: Check if subset with sum = total_sum/2 exists (divides array into equal parts). Algorithm: Use subset sum DP with targetSum=total/2. Time: O(n·sum/2) | Space: O(n·sum) + stack",
      },
      {
        name: "Count Subsets with Target Sum (Negative Numbers)",
        difficulty: "Hard",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/1-Knapsack/3-count-of-subset-sum/top-down-negative.py",
        notes: "Key insight: Count ways to form target sum with negative numbers—memoize on (n, targetSum). Algorithm: Include or exclude each element, accumulate count of valid combinations. Time: O(n·range) | Space: O(n·range) + stack",
      },
      {
        name: "Rod Cutting (Bottom-Up Unbounded Knapsack)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/2-Unbounded-Knapsack/1-rod-cutting-bottomup.py",
        notes: "Key insight: Cut rod into pieces to maximize profit (unbounded—can use same piece multiple times). Algorithm: Bottom-up DP where dp[length]=max(profit[piece]+dp[remaining_length]). Time: O(n²) | Space: O(n)",
      },
      {
        name: "Print LCS (Longest Common Subsequence)",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/3-LCS/3-print-lcs.py",
        notes: "Key insight: Use DP to compute LCS length, then backtrack to reconstruct string. Algorithm: Build LCS length table; trace back matching characters. Time: O(m·n) table + O(m+n) reconstruction | Space: O(m·n)",
      },
      {
        name: "Print LCS Practice",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "DP/3-LCS/print-lcs-practice.py",
        notes: "Key insight: Two approaches—direct string concatenation (slow) vs length table + backtrack (fast). Algorithm: Store lengths in dp[n][m], backtrack to find LCS. Time: O(m·n) | Space: O(m·n)",
      },
      {
        name: "Combination Sum (Unbounded Knapsack)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/combination-sum/",
        leetcodeNum: 39,
        file: "DP/Combination-sum.py",
        notes: "Key insight: Find all combinations that sum to target (reuse candidates). Algorithm: Backtracking with decision to use same candidate multiple times. Time: O(N^T/M) where N=candidates, T=target, M=min value | Space: O(T/M)",
      },
    ],
  },

  {
    id: "backtracking",
    name: "Backtracking",
    color: "#54A0FF",
    emoji: "↩️",
    ring: "outer",
    tips: [
      "Template: choose → explore recursively → unchoose (backtrack)",
      "Build incrementally, abandon paths that violate constraints (pruning)",
      "Use start index in for loop to avoid using the same element twice",
      "For duplicates: sort array first, then skip nums[i]==nums[i-1] at same recursion level",
      "Subsets: each element is included or excluded — think binary decisions",
    ],
    problems: [
      {
        name: "Subsets",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/subsets/",
        leetcodeNum: 78,
        file: "Backtracking/1-subset.py",
        notes: "Generate all 2^n subsets.\n\nAlgorithm:\n• At each index: include element OR skip it\n• backtrack(start, current):\n  - Add current to result (every partial result is a subset!)\n  - For i from start to n:\n    • current.append(nums[i])\n    • backtrack(i+1, current)\n    • current.pop()  ← backtrack\n\nNote: result is added at every call, not just leaf nodes.\n\nTime: O(n * 2^n) | Space: O(n) recursion depth",
      },
      {
        name: "Subsets with Duplicates",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/subsets-ii/",
        leetcodeNum: 90,
        file: "Backtracking/2-subset-with-dup.py",
        notes: "Same as Subsets but skip duplicate choices at the same level.\n\nCrucial: sort first!\n\nSkip condition: if i > start and nums[i] == nums[i-1]: continue\n\nWhy i > start? The first occurrence of a value at this level is fine.\nOnly skip if it's the same value as the previous choice at this same recursion level.\n\nTime: O(n * 2^n) | Space: O(n)",
      },
      {
        name: "Permutations",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/permutations/",
        leetcodeNum: 46,
        file: "Backtracking/permutation.py",
        notes: "Generate all n! permutations.\n\nApproach 1 – Used array:\n• used[] tracks which elements are in current permutation\n• For each unused element: use it, recurse, un-use it\n\nApproach 2 – Swap:\n• backtrack(start): if start==n, add to result\n• For i from start to n:\n  - Swap nums[start] and nums[i]\n  - backtrack(start+1)\n  - Swap back\n\nTime: O(n * n!) | Space: O(n)",
      },
      {
        name: "Generate Parentheses",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/generate-parentheses/",
        leetcodeNum: 22,
        file: "Recursion/generate-paranthesis.py",
        notes: "Generate all valid combinations of n pairs of parentheses.\n\nRules (pruning):\n• Add '(' if open < n\n• Add ')' if close < open  (ensures we never close before opening)\n• Base: if len(current) == 2n, add to result\n\nThis generates ONLY valid strings — no invalid ones created.\n\nTotal valid combos = Catalan number C(n) ≈ 4^n / (n^1.5 * √π)\n\nTime: O(4^n / √n) | Space: O(n)",
      },
      {
        name: "Maximum Number with K Swaps",
        difficulty: "Medium",
        leetcode: null,
        leetcodeNum: null,
        file: "Backtracking/3-k-swaps.py",
        notes: "Key insight: Greedily swap largest elements forward using backtracking. Algorithm: At each position, find max element from current to end, swap if greater, recurse with k-1 swaps. Time: O(n²·k) | Space: O(n)",
      },
      {
        name: "Increasing Order Numbers",
        difficulty: "Easy",
        leetcode: null,
        leetcodeNum: null,
        file: "Backtracking/4-increasing-order-num.py",
        notes: "Key insight: Generate all n-digit numbers with strictly increasing digits. Algorithm: Backtracking with start index constraint—each digit must be greater than previous. Time: O(2^n) | Space: O(n)",
      },
    ],
  },

  {
    id: "sliding-window",
    name: "Sliding Window",
    color: "#9B59B6",
    emoji: "🪟",
    ring: "outer",
    tips: [
      "Fixed window: advance both left and right together after window fills",
      "Variable window: always expand right; shrink left only when constraint violated",
      "\"Exactly K\" trick: count(at most K) − count(at most K−1)",
      "Use a hash map/array to track character frequencies in the window",
      "Result updated after expanding (max problems) or after shrinking (min problems)",
    ],
    problems: [
      {
        name: "Max Subarray Sum (Fixed)",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/maximum-average-subarray-i/",
        leetcodeNum: 643,
        file: "Sliding window/01-maxSubArraySum.py",
        notes: "Fixed window of size k.\n\nAlgorithm:\n• Compute sum of first k elements\n• Slide: add new right element, subtract leftmost element\n• Track max sum throughout\n\nFor variable-size max subarray (no fixed k):\n• Use Kadane's algorithm: curr = max(nums[i], curr+nums[i])\n• This handles the \"start fresh or extend\" decision\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Count Subarrays (Dynamic)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/count-number-of-nice-subarrays/",
        leetcodeNum: 1248,
        file: "Sliding window/02-numOfSubArrays.py",
        notes: "Count subarrays satisfying a constraint.\n\nDynamic window template:\n• left = 0, result = 0\n• For right from 0 to n:\n  - Expand: include nums[right] in window\n  - Shrink: while constraint violated: remove nums[left], left++\n  - Count: result += (right - left + 1)  ← subarrays ending at right\n\nFor \"exactly K\": atMost(K) - atMost(K-1)\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Repeated DNA Sequences",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/repeated-dna-sequences/",
        leetcodeNum: 187,
        file: "Sliding window/03-DNA.py",
        notes: "Find all 10-letter sequences appearing more than once.\n\nAlgorithm (fixed window of 10):\n• seen = set(), result = set()\n• For i from 0 to len(s)-10:\n  - substr = s[i:i+10]\n  - If substr in seen: add to result\n  - Else: add to seen\n\nOptimization: use rolling hash to avoid O(10) substring creation — compute hash in O(1) per step.\n\nTime: O(n*L) naive, O(n) with rolling hash | Space: O(n)",
      },
    ],
  },

  {
    id: "strings",
    name: "Strings",
    color: "#1ABC9C",
    emoji: "📝",
    ring: "outer",
    tips: [
      "Python strings are immutable — use list + \"\".join(lst) for modifications",
      "sorted(word) or tuple(Counter(word)) as key for anagram grouping",
      "Two-pointer for palindrome checks (expand from center)",
      "ord(c) - ord('a') converts char to 0-25 index",
      "str.split() with no arg splits on any whitespace and strips empty strings",
    ],
    problems: [
      {
        name: "Group Anagrams",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/group-anagrams/",
        leetcodeNum: 49,
        file: "groupAnagram/02-optimal-sol.py",
        notes: "Anagrams have the same sorted form — use it as a key.\n\nApproach 1 – Sort as key:\n• key = tuple(sorted(word))\n• Group by key using defaultdict(list)\n• O(n * k log k) where k = max word length\n\nApproach 2 – Count array as key (faster for large alphabets):\n• key = tuple([0]*26 with counts filled in)\n• O(n * k) with no sorting\n\nReturn list of groups.",
      },
      {
        name: "Valid Anagram",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/valid-anagram/",
        leetcodeNum: 242,
        file: "Strings/1-leetcode.py",
        notes: "Check if two strings are anagrams of each other.\n\nApproach 1: Sort both, compare → O(n log n)\n\nApproach 2 – Count array:\n• counts = [0]*26\n• For c in s: counts[ord(c)-ord('a')] += 1\n• For c in t: counts[ord(c)-ord('a')] -= 1\n• Return all(c==0 for c in counts)\n\nApproach 3: Counter(s) == Counter(t) → Pythonic\n\nTime: O(n) | Space: O(1) (26-letter alphabet)",
      },
    ],
  },

  {
    id: "merge-intervals",
    name: "Merge Intervals",
    color: "#E67E22",
    emoji: "📏",
    ring: "outer",
    tips: [
      "Sort by START TIME for merging problems",
      "Sort by END TIME for greedy non-overlapping (meeting rooms, etc.)",
      "Two intervals [a,b] and [c,d] overlap if a <= d AND c <= b",
      "Line sweep: +1 event at start, -1 event at end; sort and process",
      "After sorting, only compare with the LAST merged interval",
    ],
    problems: [
      {
        name: "Merge Intervals",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/merge-intervals/",
        leetcodeNum: 56,
        file: "MergeIntervals/1-merge-intervals.py",
        notes: "Sort by start time, then greedily merge.\n\nAlgorithm:\n• Sort intervals by start\n• result = [intervals[0]]\n• For each interval [s, e]:\n  - If s <= result[-1][1]: overlap! extend result[-1][1] = max(result[-1][1], e)\n  - Else: no overlap, append [s, e] to result\n\nWhy max? The new interval might be fully contained within the last merged one.\n\nTime: O(n log n) | Space: O(n)",
      },
      {
        name: "Insert Interval",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/insert-interval/",
        leetcodeNum: 57,
        file: "MergeIntervals/2-insert-interval.py",
        notes: "Insert a new interval and merge if needed. Assumes input is sorted.\n\nThree phases:\n1. Add all intervals ending before new one starts (end < new_start)\n2. Merge all overlapping intervals with new: new = [min(starts), max(ends)]\n   - While start <= new_end: merge and advance\n3. Add remaining non-overlapping intervals\n\nTime: O(n) | Space: O(n)",
      },
      {
        name: "Erase Overlapping Intervals",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/non-overlapping-intervals/",
        leetcodeNum: 435,
        file: "MergeIntervals/4-erase-overlapping-interval.py",
        notes: "Minimum intervals to remove so no two overlap.\n\nGreedy: sort by END TIME, keep as many non-overlapping intervals as possible.\n\nAlgorithm:\n• Sort by end\n• prev_end = intervals[0][1], count = 0\n• For each interval [s, e] from index 1:\n  - If s < prev_end: OVERLAP → remove (count++), keep shorter end (min)\n  - Else: no overlap, update prev_end = e\n\nWhy sort by end? Keeping earliest-ending interval leaves most room for others.\n\nTime: O(n log n) | Space: O(1)",
      },
      {
        name: "Line Sweep (Overlap Count)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/meeting-rooms-ii/",
        leetcodeNum: 253,
        file: "MergeIntervals/3-line-sweep.py",
        notes: "Count maximum overlapping intervals at any point in time.\n\nLine Sweep algorithm:\n• For each interval [s, e]: create events (s, +1) and (e, -1)\n• Sort all events by time\n• Sweep through: maintain running sum (active intervals)\n• Maximum running sum = answer\n\nTie-breaking: process end events before start events at same time (e.g. sort by (time, type)).\n\nTime: O(n log n) | Space: O(n)",
      },
    ],
  },

  {
    id: "range-query",
    name: "Range Queries",
    color: "#27AE60",
    emoji: "📐",
    ring: "outer",
    tips: [
      "Static array, range sum → Prefix Sum: O(n) build, O(1) query",
      "Dynamic array (updates + queries) → Segment Tree or BIT: O(log n) both",
      "BIT simpler to code; Segment Tree more flexible (min/max/custom merge)",
      "BIT update: i += i & (-i) to move to next responsible range",
      "BIT query: i -= i & (-i) to move to parent prefix",
    ],
    problems: [
      {
        name: "Range Sum Query (Prefix)",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/range-sum-query-immutable/",
        leetcodeNum: 303,
        file: "prefixSum/01-sumRange.py",
        notes: "Immutable array — build prefix sum once, answer queries in O(1).\n\nBuild:\n• prefix[0] = 0\n• prefix[i] = prefix[i-1] + nums[i-1]  (1-indexed)\n\nQuery [l, r]:\n• return prefix[r+1] - prefix[l]\n\nFor subarray sum == k:\n• Use hash map: count[prefix[i] - k] gives subarrays ending at i\n• Initialize count = {0: 1}\n\nTime: O(n) build, O(1) query | Space: O(n)",
      },
      {
        name: "Segment Tree",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/range-sum-query-mutable/",
        leetcodeNum: 307,
        file: "Range-Query/01-segment-tree.py",
        notes: "Array-based tree (size 4n) for range queries with point updates.\n\nStructure:\n• Node at index i: left child at 2i, right child at 2i+1\n• Leaf nodes hold single values; internal nodes hold range aggregates\n\nOperations:\n• build(node, start, end): fills tree bottom-up\n• update(node, start, end, idx, val): update leaf, recompute ancestors\n• query(node, start, end, l, r): split query at tree nodes\n\nAll operations: O(log n) | Space: O(4n)",
      },
      {
        name: "Binary Indexed Tree (Fenwick)",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/range-sum-query-mutable/",
        leetcodeNum: 307,
        file: "Range-Query/02-binary-index-tree.md",
        notes: "Simpler than segment tree for prefix sum/XOR. 1-indexed!\n\nUpdate(i, delta):\n• while i <= n: tree[i] += delta; i += i & (-i)\n• i & (-i) isolates the lowest set bit\n\nPrefix Query(i):\n• s = 0; while i > 0: s += tree[i]; i -= i & (-i)\n• Returns sum of first i elements\n\nRange query [l,r] = query(r) - query(l-1)\n\nTime: O(n log n) build, O(log n) update/query | Space: O(n)",
      },
    ],
  },

  {
    id: "recursion",
    name: "Recursion",
    color: "#F39C12",
    emoji: "🔄",
    ring: "outer",
    tips: [
      "Define the base case first — what stops the recursion?",
      "Trust the recursion: assume recursive call returns correct result",
      "Python default recursion limit is 1000 (use sys.setrecursionlimit if needed)",
      "Recursion tree: each node is a call; leaves are base cases",
      "T(n) = 2T(n/2) + O(n) → O(n log n) by Master Theorem",
      "Draw the call tree to compute time complexity",
    ],
    problems: [
      {
        name: "Power Function (Fast Exponentiation)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/powx-n/",
        leetcodeNum: 50,
        file: "Recursion/pow(a,b).py",
        notes: "Compute a^b in O(log b) instead of O(b).\n\nKey insight:\n• a^b = (a^(b/2))² if b is even\n• a^b = a × (a^(b/2))² if b is odd\n\nAlgorithm:\n• if b == 0: return 1\n• half = pow(a, b//2)\n• if b % 2 == 0: return half * half\n• else: return a * half * half\n\nHandle negative: pow(a, -n) = 1/pow(a, n)\n\nTime: O(log n) | Space: O(log n) stack",
      },
      {
        name: "Sort Stack Using Recursion",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/sort-an-array/",
        leetcodeNum: 912,
        file: "Recursion/sort-stack-using-recursion.py",
        notes: "Sort a stack using only recursion (no loops allowed).\n\nTwo recursive functions:\n1. sort(stack):\n   - Pop top element\n   - Recursively sort the remaining stack\n   - Insert the popped element in sorted position\n\n2. insertSorted(stack, elem):\n   - If stack empty or top <= elem: push elem\n   - Else: pop top, insertSorted(stack, elem), push top back\n\nTime: O(n²) | Space: O(n) stack frames",
      },
      {
        name: "Find All Substrings",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/subsets/",
        leetcodeNum: 78,
        file: "Recursion/find-all-strings.py",
        notes: "Generate all substrings of a string using recursion.\n\nApproach (include/exclude each char):\n• At each index i, either include s[i] in current string or skip\n• Build strings left to right, collecting when all chars processed\n\nAlternative: two nested loops O(n²)\n• For start in range(n):\n  - For end in range(start+1, n+1):\n    - yield s[start:end]\n\nTime: O(n * 2^n) for recursive | O(n²) for iterative",
      },
    ],
  },

  {
    id: "maths",
    name: "Maths",
    color: "#2980B9",
    emoji: "🔢",
    ring: "outer",
    tips: [
      "Matrix 4-directions: dr=[0,0,1,-1], dc=[1,-1,0,0]",
      "Matrix 8-directions: all (dr,dc) combinations of {-1,0,1} except (0,0)",
      "Check bounds: 0 <= r+dr < rows AND 0 <= c+dc < cols",
      "Reverse a number: digit = n%10, n //= 10, reversed = reversed*10 + digit",
      "Modular arithmetic: (a*b)%m = ((a%m)*(b%m))%m",
    ],
    problems: [
      {
        name: "Reverse Integer",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/reverse-integer/",
        leetcodeNum: 7,
        file: "Maths/2-reverse.py",
        notes: "Reverse digits, handle overflow.\n\nAlgorithm:\n• sign = -1 if x < 0 else 1; x = abs(x)\n• result = 0\n• While x > 0:\n  - result = result * 10 + x % 10\n  - x //= 10\n• result *= sign\n• If result > 2^31 - 1 or result < -2^31: return 0\n\nIn Python, integers don't overflow — check manually against INT_MAX.\n\nTime: O(log x) | Space: O(1)",
      },
      {
        name: "2D Matrix Directions",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/spiral-matrix/",
        leetcodeNum: 54,
        file: "Maths/1-2D-matrix-direction.py",
        notes: "Standard template for grid traversal.\n\n4-directional:\n• dr = [-1, 0, 1, 0]  (up, right, down, left)\n• dc = [0, 1, 0, -1]\n\n8-directional:\n• for dr in [-1,0,1]:\n  - for dc in [-1,0,1]:\n    - if dr==0 and dc==0: continue\n\nBounds check:\n• nr, nc = r+dr[d], c+dc[d]\n• if 0 <= nr < rows and 0 <= nc < cols: process (nr, nc)",
      },
    ],
  },

  {
    id: "bit-manipulation",
    name: "Bit Manipulation",
    color: "#8E44AD",
    emoji: "⚙️",
    ring: "outer",
    tips: [
      "XOR: a^a=0, a^0=a — use to cancel pairs and find unique element",
      "Check kth bit: (n >> k) & 1",
      "Set kth bit: n | (1 << k)",
      "Clear kth bit: n & ~(1 << k)",
      "n & (n-1) clears the lowest set bit (Brian Kernighan's trick)",
      "n & (-n) isolates the lowest set bit",
      "Count set bits: bin(n).count(\"1\") or Brian Kernighan loop",
    ],
    problems: [
      {
        name: "Missing Number (XOR)",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/missing-number/",
        leetcodeNum: 268,
        file: "BitManipulation/1-missing-number.py",
        notes: "Find missing number in [0,n] using XOR.\n\nKey insight: a^a = 0, 0^a = a\n• XOR all indices [0,n] with all array values\n• Paired values cancel out, leaving only the missing number\n\nAlgorithm:\n• result = n  (start with n since array has indices 0..n-1)\n• For i, val in enumerate(nums):\n  - result ^= i ^ val\n• Return result\n\nAlternative: expected_sum = n*(n+1)//2 - sum(nums)\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Single Number",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/single-number/",
        leetcodeNum: 136,
        file: "BitManipulation/3-pattern2.py",
        notes: "Find the one element that appears once (all others appear twice).\n\nXOR all elements — duplicates cancel:\n• 2^2 = 0, 3^3 = 0, so only the unique element remains\n• result = 0\n• For num in nums: result ^= num\n• Return result\n\nFor Single Number II (appears once, others 3 times):\n• Count bits modulo 3 — bits from unique number survive\n\nTime: O(n) | Space: O(1)",
      },
    ],
  },

  {
    id: "cyclic-sort",
    name: "Cyclic Sort",
    color: "#C0392B",
    emoji: "🔃",
    ring: "outer",
    tips: [
      "Pattern: values in range [1,n] or [0,n-1] → place each at its correct index",
      "Correct position for value v: index v-1 (for [1,n] range)",
      "Swap nums[i] with nums[nums[i]-1] until nums[i] is at its correct spot",
      "O(n) despite nested-looking loop: each element moves to correct position at most once",
      "After sort, scan for where nums[i] != i+1 — those positions hold answers",
    ],
    problems: [
      {
        name: "Missing Number (Cyclic Sort)",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/missing-number/",
        leetcodeNum: 268,
        file: "Cyclic Sort/when-to-use.md",
        notes: "Place each number at its correct index, then find the gap.\n\nAlgorithm:\n• i = 0; while i < n:\n  - j = nums[i] - 1  (correct index for nums[i])\n  - if nums[i] < n and nums[i] != nums[j]: swap nums[i], nums[j]\n  - else: i++\n• After sorting:\n  - For i in range(n): if nums[i] != i+1: return i+1\n• Return n  (if all 1..n present, missing is n+1)\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Find All Duplicates (Cyclic)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
        leetcodeNum: 442,
        file: "Cyclic Sort/when-to-use.md",
        notes: "Cyclic sort, then find positions where number doesn't match index.\n\nAlgorithm:\n• Cyclic sort: place nums[i] at index nums[i]-1\n• After sorting: scan array\n  - If nums[i] != i+1: nums[i] is a duplicate (it's occupying wrong spot)\n  - Add nums[i] to result\n\nWhy it works: each duplicate leaves one valid position occupied by the wrong number.\n\nTime: O(n) | Space: O(1) (output doesn't count)",
      },
    ],
  },

  {
    id: "prefix-sum",
    name: "Prefix Sum",
    color: "#16A085",
    emoji: "∑",
    ring: "outer",
    tips: [
      "Build: prefix[0]=0, prefix[i] = prefix[i-1] + nums[i-1]  (1-indexed)",
      "Range query [l, r] = prefix[r+1] - prefix[l]",
      "With hash map: find subarrays with given sum in O(n)",
      "prefix[r] - prefix[l] == k  ↔  prefix[l] = prefix[r] - k",
      "Initialize count map with {0: 1} for subarrays starting at index 0",
    ],
    problems: [
      {
        name: "Range Sum Query",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/range-sum-query-immutable/",
        leetcodeNum: 303,
        file: "prefixSum/01-sumRange.py",
        notes: "Build once, query in O(1).\n\nBuild:\n• self.prefix = [0] * (n+1)\n• For i in range(n): prefix[i+1] = prefix[i] + nums[i]\n\nQuery sumRange(l, r):\n• return prefix[r+1] - prefix[l]\n\nThis is the foundation for many harder problems (2D prefix sum, etc.)\n\nTime: O(n) build, O(1) query | Space: O(n)",
      },
      {
        name: "Subarray Sum Equals K",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/subarray-sum-equals-k/",
        leetcodeNum: 560,
        file: "prefixSum/01-sumRange.py",
        notes: "Count subarrays with sum exactly k.\n\nAlgorithm:\n• count = defaultdict(int); count[0] = 1\n• prefix_sum = 0; result = 0\n• For each num:\n  - prefix_sum += num\n  - result += count[prefix_sum - k]  ← how many prefixes sum to prefix-k\n  - count[prefix_sum] += 1\n\nKey: count[prefix_sum - k] tells how many previous prefixes, when subtracted, give sum k.\n\nTime: O(n) | Space: O(n)",
      },
    ],
  },

  {
    id: "sorting",
    name: "Sorting",
    color: "#D4AC0D",
    emoji: "↕️",
    ring: "outer",
    tips: [
      "Python sort is TimSort: O(n log n) worst case, stable",
      "arr.sort(key=lambda x: x[1]) for custom sort by second element",
      "Counting sort: O(n+k) for small integer ranges",
      "Merge sort divides and conquers — stable, O(n log n) guaranteed",
      "QuickSort O(n log n) average but O(n²) worst case (avoid with random pivot)",
    ],
    problems: [
      {
        name: "Sort Colors (Dutch Flag)",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/sort-colors/",
        leetcodeNum: 75,
        file: "sorting/",
        notes: "Sort 0s, 1s, 2s in one pass (Dutch National Flag problem).\n\nThree-pointer approach:\n• low=0, mid=0, high=n-1\n• While mid <= high:\n  - If nums[mid]==0: swap(low,mid), low++, mid++\n  - If nums[mid]==1: mid++ (already in place)\n  - If nums[mid]==2: swap(mid,high), high--  (don't increment mid!)\n\nWhy not mid++ when swapping with high? The swapped element might be 0 or 2.\n\nTime: O(n) | Space: O(1)",
      },
    ],
  },

  {
    id: "google",
    name: "Google / Misc",
    color: "#6C5CE7",
    emoji: "🎯",
    ring: "outer",
    tips: [
      "O(1) insert/delete/getRandom: Array + HashMap combo (swap-with-last)",
      "Consecutive sequence: use set, only start counting from sequence beginnings",
      "For greedy problems: sort by a key that maximizes your choices",
      "Climbing Stairs = Fibonacci — classic 'ways to reach' DP pattern",
    ],
    problems: [
      {
        name: "Climb Stairs",
        difficulty: "Easy",
        leetcode: "https://leetcode.com/problems/climbing-stairs/",
        leetcodeNum: 70,
        file: "google/climb-stairs.py",
        notes: "How many ways to climb n stairs taking 1 or 2 steps at a time?\n\nThis is Fibonacci!\n• dp[n] = dp[n-1] + dp[n-2]\n• Base: dp[1]=1, dp[2]=2\n\nSpace optimized:\n• a, b = 1, 2\n• For i in range(3, n+1): a, b = b, a+b\n• Return b\n\nGeneralization: if can take 1..k steps, use window sum of last k dp values.\n\nTime: O(n) | Space: O(1)",
      },
      {
        name: "Longest Consecutive Sequence",
        difficulty: "Medium",
        leetcode: "https://leetcode.com/problems/longest-consecutive-sequence/",
        leetcodeNum: 128,
        file: "google/longest-consecutive-seq.py",
        notes: "Find longest consecutive sequence in O(n) (no sorting).\n\nKey insight: only start counting from sequence beginnings.\n\nAlgorithm:\n• Add all numbers to a set\n• For each num: only proceed if (num-1) NOT in set (this is a start)\n• Count up while (num+streak) in set\n• Update max streak\n\nWithout the \"only start from beginning\" check: O(n²).\n\nTime: O(n) | Space: O(n)",
      },
      {
        name: "Candy",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/candy/",
        leetcodeNum: 135,
        file: "google/candy.py",
        notes: "Minimum candies: child with higher rating than neighbor gets more.\n\nTwo-pass greedy:\n1. Left to right: if ratings[i] > ratings[i-1]: candies[i] = candies[i-1]+1\n   • Handles left neighbor constraint\n\n2. Right to left: if ratings[i] > ratings[i+1]: candies[i] = max(candies[i], candies[i+1]+1)\n   • Handles right neighbor constraint\n   • max() preserves left-pass results\n\nReturn sum of candies.\n\nTime: O(n) | Space: O(n)",
      },
      {
        name: "Insert Delete GetRandom O(1)",
        difficulty: "Hard",
        leetcode: "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/",
        leetcodeNum: 381,
        file: "google/insert-delete-o(1).md",
        notes: "O(1) insert, remove, and getRandom.\n\nData structure:\n• vals = [] (array for O(1) random access)\n• idx_map = {val: set of indices}\n\nInsert(val):\n• Append to vals, add index to idx_map[val]\n\nRemove(val):\n• Get any index i from idx_map[val]\n• Swap vals[i] with vals[-1]\n• Update idx_map for the swapped element\n• Remove last element, pop from idx_map[val]\n\nGetRandom(): random.choice(vals)\n\nTime: all O(1) | Space: O(n)",
      },
    ],
  },

];
